# Generated by Django 3.1.1 on 2020-09-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeimagemodel',
            name='pipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipe_images', to='pipe.pipemodel', verbose_name='Труба'),
        ),
    ]
